{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "f599b3c7-fbe7-4e4e-a655-23c84cc68fd1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: streamlit in c:\\users\\hp\\anaconda3\\lib\\site-packages (1.30.0)\n",
      "Requirement already satisfied: altair<6,>=4.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (5.0.1)\n",
      "Requirement already satisfied: blinker<2,>=1.0.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (1.6.2)\n",
      "Requirement already satisfied: cachetools<6,>=4.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (4.2.2)\n",
      "Requirement already satisfied: click<9,>=7.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (8.1.7)\n",
      "Requirement already satisfied: importlib-metadata<8,>=1.4 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (7.0.1)\n",
      "Collecting numpy<2,>=1.19.3 (from streamlit)\n",
      "  Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)\n",
      "     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--\n",
      "     ------------ ------------------------- 20.5/61.0 kB 320.0 kB/s eta 0:00:01\n",
      "     ------------------------- ------------ 41.0/61.0 kB 388.9 kB/s eta 0:00:01\n",
      "     -------------------------------------- 61.0/61.0 kB 461.8 kB/s eta 0:00:00\n",
      "Requirement already satisfied: packaging<24,>=16.8 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (23.1)\n",
      "Requirement already satisfied: pandas<3,>=1.3.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (2.1.4)\n",
      "Requirement already satisfied: pillow<11,>=7.1.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (10.2.0)\n",
      "Requirement already satisfied: protobuf<5,>=3.20 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (3.20.3)\n",
      "Requirement already satisfied: pyarrow>=6.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (14.0.2)\n",
      "Requirement already satisfied: python-dateutil<3,>=2.7.3 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (2.8.2)\n",
      "Requirement already satisfied: requests<3,>=2.27 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (2.31.0)\n",
      "Requirement already satisfied: rich<14,>=10.14.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (13.3.5)\n",
      "Requirement already satisfied: tenacity<9,>=8.1.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (8.2.2)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.3.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (4.9.0)\n",
      "Requirement already satisfied: tzlocal<6,>=1.1 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (2.1)\n",
      "Requirement already satisfied: validators<1,>=0.2 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (0.18.2)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (3.1.37)\n",
      "Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (0.8.0)\n",
      "Requirement already satisfied: tornado<7,>=6.0.3 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (6.3.3)\n",
      "Requirement already satisfied: watchdog>=2.1.5 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from streamlit) (2.1.6)\n",
      "Requirement already satisfied: jinja2 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (3.1.3)\n",
      "Requirement already satisfied: jsonschema>=3.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (4.19.2)\n",
      "Requirement already satisfied: toolz in c:\\users\\hp\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (0.12.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\hp\\anaconda3\\lib\\site-packages (from click<9,>=7.0->streamlit) (0.4.6)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)\n",
      "Requirement already satisfied: zipp>=0.5 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from importlib-metadata<8,>=1.4->streamlit) (3.17.0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3.post1)\n",
      "Requirement already satisfied: tzdata>=2022.1 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from python-dateutil<3,>=2.7.3->streamlit) (1.16.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2.0.7)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2024.2.2)\n",
      "Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from rich<14,>=10.14.0->streamlit) (2.2.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from rich<14,>=10.14.0->streamlit) (2.15.1)\n",
      "Requirement already satisfied: decorator>=3.4.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from validators<1,>=0.2->streamlit) (5.1.1)\n",
      "Requirement already satisfied: smmap<5,>=3.0.1 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)\n",
      "Requirement already satisfied: attrs>=22.2.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.2.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)\n",
      "Requirement already satisfied: mdurl~=0.1 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.0)\n",
      "Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl (15.8 MB)\n",
      "   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--\n",
      "    --------------------------------------- 0.3/15.8 MB 10.6 MB/s eta 0:00:02\n",
      "   - -------------------------------------- 0.7/15.8 MB 7.8 MB/s eta 0:00:02\n",
      "   --- ------------------------------------ 1.3/15.8 MB 10.6 MB/s eta 0:00:02\n",
      "   ---- ----------------------------------- 1.8/15.8 MB 9.4 MB/s eta 0:00:02\n",
      "   ---- ----------------------------------- 1.9/15.8 MB 8.8 MB/s eta 0:00:02\n",
      "   ---- ----------------------------------- 1.9/15.8 MB 8.8 MB/s eta 0:00:02\n",
      "   ---- ----------------------------------- 1.9/15.8 MB 8.8 MB/s eta 0:00:02\n",
      "   ---- ----------------------------------- 2.0/15.8 MB 5.7 MB/s eta 0:00:03\n",
      "   ----- ---------------------------------- 2.0/15.8 MB 5.0 MB/s eta 0:00:03\n",
      "   ----- ---------------------------------- 2.1/15.8 MB 4.5 MB/s eta 0:00:04\n",
      "   ----- ---------------------------------- 2.1/15.8 MB 4.5 MB/s eta 0:00:04\n",
      "   ----- ---------------------------------- 2.1/15.8 MB 3.8 MB/s eta 0:00:04\n",
      "   ----- ---------------------------------- 2.1/15.8 MB 3.7 MB/s eta 0:00:04\n",
      "   ----- ---------------------------------- 2.2/15.8 MB 3.5 MB/s eta 0:00:04\n",
      "   ----- ---------------------------------- 2.2/15.8 MB 3.3 MB/s eta 0:00:05\n",
      "   ----- ---------------------------------- 2.2/15.8 MB 3.3 MB/s eta 0:00:05\n",
      "   ----- ---------------------------------- 2.2/15.8 MB 2.8 MB/s eta 0:00:05\n",
      "   ----- ---------------------------------- 2.3/15.8 MB 2.7 MB/s eta 0:00:05\n",
      "   ----- ---------------------------------- 2.3/15.8 MB 2.6 MB/s eta 0:00:06\n",
      "   ----- ---------------------------------- 2.3/15.8 MB 2.7 MB/s eta 0:00:06\n",
      "   ------ --------------------------------- 2.4/15.8 MB 2.5 MB/s eta 0:00:06\n",
      "   ------ --------------------------------- 2.4/15.8 MB 2.5 MB/s eta 0:00:06\n",
      "   ------ --------------------------------- 2.4/15.8 MB 2.3 MB/s eta 0:00:06\n",
      "   ------ --------------------------------- 2.4/15.8 MB 2.2 MB/s eta 0:00:07\n",
      "   ------ --------------------------------- 2.5/15.8 MB 2.2 MB/s eta 0:00:07\n",
      "   ------ --------------------------------- 2.5/15.8 MB 2.1 MB/s eta 0:00:07\n",
      "   ------ --------------------------------- 2.5/15.8 MB 2.1 MB/s eta 0:00:07\n",
      "   ------ --------------------------------- 2.5/15.8 MB 2.0 MB/s eta 0:00:07\n",
      "   ------ --------------------------------- 2.5/15.8 MB 2.0 MB/s eta 0:00:07\n",
      "   ------ --------------------------------- 2.5/15.8 MB 1.8 MB/s eta 0:00:08\n",
      "   ------ --------------------------------- 2.6/15.8 MB 1.8 MB/s eta 0:00:08\n",
      "   ------ --------------------------------- 2.7/15.8 MB 1.8 MB/s eta 0:00:08\n",
      "   ------- -------------------------------- 2.8/15.8 MB 1.8 MB/s eta 0:00:08\n",
      "   ------- -------------------------------- 2.9/15.8 MB 1.8 MB/s eta 0:00:08\n",
      "   ------- -------------------------------- 2.9/15.8 MB 1.8 MB/s eta 0:00:08\n",
      "   ------- -------------------------------- 3.0/15.8 MB 1.8 MB/s eta 0:00:08\n",
      "   ------- -------------------------------- 3.1/15.8 MB 1.8 MB/s eta 0:00:08\n",
      "   -------- ------------------------------- 3.2/15.8 MB 1.8 MB/s eta 0:00:07\n",
      "   -------- ------------------------------- 3.4/15.8 MB 1.9 MB/s eta 0:00:07\n",
      "   -------- ------------------------------- 3.5/15.8 MB 1.9 MB/s eta 0:00:07\n",
      "   --------- ------------------------------ 3.7/15.8 MB 1.9 MB/s eta 0:00:07\n",
      "   --------- ------------------------------ 3.8/15.8 MB 2.0 MB/s eta 0:00:07\n",
      "   --------- ------------------------------ 3.9/15.8 MB 2.0 MB/s eta 0:00:07\n",
      "   ---------- ----------------------------- 4.0/15.8 MB 1.9 MB/s eta 0:00:07\n",
      "   ---------- ----------------------------- 4.1/15.8 MB 2.0 MB/s eta 0:00:06\n",
      "   ---------- ----------------------------- 4.2/15.8 MB 2.0 MB/s eta 0:00:06\n",
      "   ---------- ----------------------------- 4.3/15.8 MB 2.0 MB/s eta 0:00:06\n",
      "   ----------- ---------------------------- 4.5/15.8 MB 2.0 MB/s eta 0:00:06\n",
      "   ----------- ---------------------------- 4.6/15.8 MB 2.0 MB/s eta 0:00:06\n",
      "   ------------ --------------------------- 4.8/15.8 MB 2.1 MB/s eta 0:00:06\n",
      "   ------------ --------------------------- 5.0/15.8 MB 2.1 MB/s eta 0:00:06\n",
      "   ------------ --------------------------- 5.1/15.8 MB 2.1 MB/s eta 0:00:06\n",
      "   ------------- -------------------------- 5.3/15.8 MB 2.1 MB/s eta 0:00:05\n",
      "   ------------- -------------------------- 5.4/15.8 MB 2.1 MB/s eta 0:00:05\n",
      "   ------------- -------------------------- 5.5/15.8 MB 2.1 MB/s eta 0:00:05\n",
      "   -------------- ------------------------- 5.5/15.8 MB 2.1 MB/s eta 0:00:05\n",
      "   -------------- ------------------------- 5.6/15.8 MB 2.1 MB/s eta 0:00:05\n",
      "   -------------- ------------------------- 5.7/15.8 MB 2.1 MB/s eta 0:00:05\n",
      "   -------------- ------------------------- 5.8/15.8 MB 2.1 MB/s eta 0:00:05\n",
      "   -------------- ------------------------- 5.9/15.8 MB 2.1 MB/s eta 0:00:05\n",
      "   --------------- ------------------------ 5.9/15.8 MB 2.1 MB/s eta 0:00:05\n",
      "   --------------- ------------------------ 6.0/15.8 MB 2.1 MB/s eta 0:00:05\n",
      "   --------------- ------------------------ 6.1/15.8 MB 2.1 MB/s eta 0:00:05\n",
      "   --------------- ------------------------ 6.2/15.8 MB 2.1 MB/s eta 0:00:05\n",
      "   --------------- ------------------------ 6.3/15.8 MB 2.1 MB/s eta 0:00:05\n",
      "   ---------------- ----------------------- 6.4/15.8 MB 2.1 MB/s eta 0:00:05\n",
      "   ---------------- ----------------------- 6.5/15.8 MB 2.1 MB/s eta 0:00:05\n",
      "   ---------------- ----------------------- 6.6/15.8 MB 2.1 MB/s eta 0:00:05\n",
      "   ----------------- ---------------------- 6.7/15.8 MB 2.1 MB/s eta 0:00:05\n",
      "   ----------------- ---------------------- 6.9/15.8 MB 2.1 MB/s eta 0:00:05\n",
      "   ----------------- ---------------------- 7.0/15.8 MB 2.1 MB/s eta 0:00:05\n",
      "   ------------------ --------------------- 7.1/15.8 MB 2.1 MB/s eta 0:00:05\n",
      "   ------------------ --------------------- 7.3/15.8 MB 2.1 MB/s eta 0:00:04\n",
      "   ------------------ --------------------- 7.4/15.8 MB 2.2 MB/s eta 0:00:04\n",
      "   ------------------- -------------------- 7.6/15.8 MB 2.2 MB/s eta 0:00:04\n",
      "   ------------------- -------------------- 7.8/15.8 MB 2.2 MB/s eta 0:00:04\n",
      "   -------------------- ------------------- 8.0/15.8 MB 2.2 MB/s eta 0:00:04\n",
      "   -------------------- ------------------- 8.2/15.8 MB 2.3 MB/s eta 0:00:04\n",
      "   --------------------- ------------------ 8.3/15.8 MB 2.3 MB/s eta 0:00:04\n",
      "   --------------------- ------------------ 8.4/15.8 MB 2.3 MB/s eta 0:00:04\n",
      "   --------------------- ------------------ 8.6/15.8 MB 2.3 MB/s eta 0:00:04\n",
      "   ---------------------- ----------------- 8.7/15.8 MB 2.3 MB/s eta 0:00:04\n",
      "   ---------------------- ----------------- 8.8/15.8 MB 2.3 MB/s eta 0:00:04\n",
      "   ---------------------- ----------------- 8.9/15.8 MB 2.3 MB/s eta 0:00:04\n",
      "   ---------------------- ----------------- 9.1/15.8 MB 2.3 MB/s eta 0:00:03\n",
      "   ----------------------- ---------------- 9.2/15.8 MB 2.3 MB/s eta 0:00:03\n",
      "   ----------------------- ---------------- 9.4/15.8 MB 2.3 MB/s eta 0:00:03\n",
      "   ------------------------ --------------- 9.5/15.8 MB 2.3 MB/s eta 0:00:03\n",
      "   ------------------------ --------------- 9.7/15.8 MB 2.3 MB/s eta 0:00:03\n",
      "   ------------------------ --------------- 9.8/15.8 MB 2.3 MB/s eta 0:00:03\n",
      "   ------------------------- -------------- 10.0/15.8 MB 2.4 MB/s eta 0:00:03\n",
      "   ------------------------- -------------- 10.1/15.8 MB 2.4 MB/s eta 0:00:03\n",
      "   ------------------------- -------------- 10.3/15.8 MB 2.4 MB/s eta 0:00:03\n",
      "   -------------------------- ------------- 10.5/15.8 MB 2.4 MB/s eta 0:00:03\n",
      "   -------------------------- ------------- 10.6/15.8 MB 2.3 MB/s eta 0:00:03\n",
      "   --------------------------- ------------ 10.8/15.8 MB 2.3 MB/s eta 0:00:03\n",
      "   --------------------------- ------------ 11.1/15.8 MB 2.3 MB/s eta 0:00:03\n",
      "   ---------------------------- ----------- 11.3/15.8 MB 2.3 MB/s eta 0:00:02\n",
      "   ----------------------------- ---------- 11.6/15.8 MB 2.3 MB/s eta 0:00:02\n",
      "   ----------------------------- ---------- 11.8/15.8 MB 2.3 MB/s eta 0:00:02\n",
      "   ------------------------------ --------- 12.0/15.8 MB 2.3 MB/s eta 0:00:02\n",
      "   ------------------------------- -------- 12.3/15.8 MB 2.4 MB/s eta 0:00:02\n",
      "   ------------------------------- -------- 12.5/15.8 MB 2.6 MB/s eta 0:00:02\n",
      "   -------------------------------- ------- 12.8/15.8 MB 2.9 MB/s eta 0:00:02\n",
      "   -------------------------------- ------- 12.9/15.8 MB 3.0 MB/s eta 0:00:01\n",
      "   --------------------------------- ------ 13.1/15.8 MB 3.1 MB/s eta 0:00:01\n",
      "   --------------------------------- ------ 13.3/15.8 MB 3.1 MB/s eta 0:00:01\n",
      "   --------------------------------- ------ 13.4/15.8 MB 3.1 MB/s eta 0:00:01\n",
      "   ---------------------------------- ----- 13.5/15.8 MB 3.1 MB/s eta 0:00:01\n",
      "   ---------------------------------- ----- 13.7/15.8 MB 3.1 MB/s eta 0:00:01\n",
      "   ---------------------------------- ----- 13.8/15.8 MB 3.1 MB/s eta 0:00:01\n",
      "   ----------------------------------- ---- 13.9/15.8 MB 3.1 MB/s eta 0:00:01\n",
      "   ----------------------------------- ---- 14.0/15.8 MB 3.1 MB/s eta 0:00:01\n",
      "   ----------------------------------- ---- 14.1/15.8 MB 3.1 MB/s eta 0:00:01\n",
      "   ----------------------------------- ---- 14.2/15.8 MB 3.1 MB/s eta 0:00:01\n",
      "   ------------------------------------ --- 14.3/15.8 MB 3.1 MB/s eta 0:00:01\n",
      "   ------------------------------------ --- 14.5/15.8 MB 3.1 MB/s eta 0:00:01\n",
      "   ------------------------------------- -- 14.7/15.8 MB 3.1 MB/s eta 0:00:01\n",
      "   ------------------------------------- -- 14.8/15.8 MB 3.1 MB/s eta 0:00:01\n",
      "   ------------------------------------- -- 14.9/15.8 MB 3.1 MB/s eta 0:00:01\n",
      "   -------------------------------------- - 15.0/15.8 MB 3.1 MB/s eta 0:00:01\n",
      "   -------------------------------------- - 15.2/15.8 MB 3.1 MB/s eta 0:00:01\n",
      "   -------------------------------------- - 15.3/15.8 MB 3.1 MB/s eta 0:00:01\n",
      "   ---------------------------------------  15.5/15.8 MB 3.1 MB/s eta 0:00:01\n",
      "   ---------------------------------------  15.7/15.8 MB 3.1 MB/s eta 0:00:01\n",
      "   ---------------------------------------  15.8/15.8 MB 3.2 MB/s eta 0:00:01\n",
      "   ---------------------------------------  15.8/15.8 MB 3.2 MB/s eta 0:00:01\n",
      "   ---------------------------------------  15.8/15.8 MB 3.2 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 15.8/15.8 MB 3.1 MB/s eta 0:00:00\n",
      "Installing collected packages: numpy\n",
      "  Attempting uninstall: numpy\n",
      "    Found existing installation: numpy 2.0.2\n",
      "    Uninstalling numpy-2.0.2:\n",
      "      Successfully uninstalled numpy-2.0.2\n",
      "Successfully installed numpy-1.26.4\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  WARNING: Failed to remove contents in a temporary directory 'C:\\Users\\hp\\AppData\\Local\\Temp\\pip-uninstall-0_4lfmcl'.\n",
      "  You can safely remove it manually.\n",
      "  WARNING: Failed to remove contents in a temporary directory 'C:\\Users\\hp\\anaconda3\\Lib\\site-packages\\~umpy.libs'.\n",
      "  You can safely remove it manually.\n",
      "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.\n",
      "blis 1.0.1 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.\n",
      "tensorflow-intel 2.18.0 requires keras>=3.5.0, but you have keras 2.15.0 which is incompatible.\n",
      "thinc 8.3.2 requires numpy<2.1.0,>=2.0.0; python_version >= \"3.9\", but you have numpy 1.26.4 which is incompatible.\n"
     ]
    }
   ],
   "source": [
    "!pip install streamlit\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "3be2aae5-d0e2-4116-a19a-2fe0898cc94f",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-11-11 15:10:12.964 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\hp\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator(_root_container=1, _parent=DeltaGenerator())"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import streamlit as st\n",
    "\n",
    "# Sample product data with images\n",
    "products = [\n",
    "    {\"name\": \"Smart TV\", \"category\": \"Electronics\", \"price\": 450, \"rating\": 4.5, \"image\": \"https://via.placeholder.com/150\"},\n",
    "    {\"name\": \"Running Shoes\", \"category\": \"Footwear\", \"price\": 70, \"rating\": 4.7, \"image\": \"https://via.placeholder.com/150\"},\n",
    "    {\"name\": \"Laptop\", \"category\": \"Electronics\", \"price\": 800, \"rating\": 4.8, \"image\": \"https://via.placeholder.com/150\"},\n",
    "]\n",
    "\n",
    "# CSS for styling\n",
    "st.markdown(\n",
    "    \"\"\"\n",
    "    <style>\n",
    "        .product-card {\n",
    "            border-radius: 10px;\n",
    "            background-color: #f9f9f9;\n",
    "            padding: 20px;\n",
    "            margin: 10px 0;\n",
    "            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);\n",
    "        }\n",
    "        .product-card img {\n",
    "            width: 100%;\n",
    "            border-radius: 10px;\n",
    "        }\n",
    "        .product-details {\n",
    "            text-align: center;\n",
    "        }\n",
    "        .add-cart-button {\n",
    "            background-color: #ff4b4b;\n",
    "            color: white;\n",
    "            border: none;\n",
    "            padding: 10px;\n",
    "            border-radius: 5px;\n",
    "            cursor: pointer;\n",
    "            font-size: 16px;\n",
    "            margin-top: 10px;\n",
    "        }\n",
    "        .add-cart-button:hover {\n",
    "            background-color: #ff2b2b;\n",
    "        }\n",
    "    </style>\n",
    "    \"\"\",\n",
    "    unsafe_allow_html=True\n",
    ")\n",
    "\n",
    "# Sidebar Filters\n",
    "st.sidebar.title(\"Filters\")\n",
    "category = st.sidebar.selectbox(\"Category\", [\"All\", \"Electronics\", \"Footwear\", \"Clothing\"])\n",
    "price_range = st.sidebar.slider(\"Price Range\", 0, 1000, (0, 500))\n",
    "search_query = st.sidebar.text_input(\"Search Products\", \"\")\n",
    "\n",
    "# Main Content\n",
    "st.title(\"🛒 Fancy E-Commerce Website\")\n",
    "st.subheader(\"Discover and shop your favorite products!\")\n",
    "\n",
    "# Filtered Product List\n",
    "st.write(\"### Products\")\n",
    "filtered_products = [\n",
    "    product for product in products \n",
    "    if (category == \"All\" or product[\"category\"] == category) \n",
    "    and (price_range[0] <= product[\"price\"] <= price_range[1])\n",
    "    and (search_query.lower() in product[\"name\"].lower() if search_query else True)\n",
    "]\n",
    "\n",
    "# Display Products as Cards\n",
    "for product in filtered_products:\n",
    "    # Product Card\n",
    "    st.markdown(\n",
    "        f\"\"\"\n",
    "        <div class=\"product-card\">\n",
    "            <img src=\"{product['image']}\" alt=\"{product['name']}\">\n",
    "            <div class=\"product-details\">\n",
    "                <h3>{product['name']}</h3>\n",
    "                <p>Category: {product['category']}</p>\n",
    "                <p>Price: ${product['price']}</p>\n",
    "                <p>Rating: {\"⭐\" * int(product['rating'])} ({product['rating']})</p>\n",
    "                <button class=\"add-cart-button\" onClick=\"alert('Added {product['name']} to cart!')\">Add to Cart</button>\n",
    "            </div>\n",
    "        </div>\n",
    "        \"\"\",\n",
    "        unsafe_allow_html=True\n",
    "    )\n",
    "\n",
    "# Shopping Cart Summary (optional, can be implemented using session states)\n",
    "st.sidebar.subheader(\"Shopping Cart\")\n",
    "# Placeholder for future cart implementation\n",
    "st.sidebar.text(\"No items in cart.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fffa08fc-c56b-4eff-9f51-09a30e0f8f79",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
